site/community/index.md, site/faq/index.md
The community has moved the governance documents to the docs.starlingx.io
website and this change updates the corresponding references on the
starlingx.io website.
Closes: #3
=> Fixing links to StarlingX governance

site/community/index.md, site/faq/index.md
The links to the governance documentation was updated but the reference
text remained the old information. This patch fixes that.
=> Fix governance hyperlink

site/blog/starlingx-meetup-january-2019.md
This change adds the group photo to the blog post that summarizes
the Chandler Contributor Meetup.
=> Add group photo to blog post

site/blog/starlingx-meetup-january-2019.md
Add a note about the new release cadence to highlight important
changes to how StarlingX works with upstream projects.
=> Add correction to the Contributor Meetup blog

site/blog/starlingx-denver-openinfra-summitschedule-announcement-2019.md
Adding a new blog post to announce the Open Infrastructure Summit
Denver agenda and StarlingX plans and activities during the Forum
and PTG.
=> Add blog post about Open Infra Summit schedule

site/community/index.md
I added a link to the three StarlingX contribute guides
under the "Contribute" heading of the Community page
for the StarlingX website.
Closes-Bug: #1808429
Signed-off-by: Scott Rifenbark <srifenbark@gmail.com>
=> Community: Add link for Contribute Guides.

site/faq/index.md
The link to the StarlingX Software under the "Where is the
Code" heading of the FAQ was broken (404).  I added the
correct URL.
Additionally, I spotted a typo in the following section
"Can I Contribute to It? How?" heading.  I fixed that
typo by adding a space and making the sentence end
cleaner.
Closes-Bug: #1808431
Signed-off-by: Scott Rifenbark <srifenbark@gmail.com>
=> FAQ: Fixed broken sw link and minor typo.

site/learn/index.md
I updated the overview slide deck, but forgot to update the file name in
the reference. This commit fixes that.
=> Fix file name mismatch

site/authors/curtis-collicutt.md, site/blog/starlingx-openinfra-summit-workshop-2019.md
This commit has a blog post for the upcoming STX Workshop at the Open Infra Summit in Denver.
I've also included a "byline" but it sounded like there would be some potential formatting changes around that, however I thought I'd get the post in as soon as I had it completed and make the necesary changes after initial submission.
Open to any and all changes. :)
=> Add Open Infra Summit STX Workshop blog post

site/community/index.md
Adding link to the Bitergia community metrics dashboard and change
contribute guides to contributor guides in the same section.
=> Adding info to the community tab

README.md
Add https for starlingx.io, so that it can refer to the expected site.
=> Fix the link of starlingx.io

site/.vuepress/components/HomeAnnouncement.vue, site/.vuepress/components/HomeContent.vue, site/.vuepress/components/hero.vue, site/.vuepress/theme/sass/modules/_box.scss, site/.vuepress/theme/sass/modules/_hero.scss, site/.vuepress/theme/sass/modules/_section.scss, site/authors/ian-jolliffe.md, site/blog/starlingx-second-release-intro-blog.md, site/faq/index.md, site/footer-nav.json, site/index.md, site/learn/index.md, site/software/index.md
General update notes:
- Homepage edits for 2.0 messaging
- FAQ updates to clarify 2.0 release
- Software page - add video, clean up columns
- Learn - clean up and messaging updates
Referencing the attached word doc:
P1 
-- Home -Integration of open source section not included until we get signoff on logo usage
-- Home - New diagram not available as yet
P3
-- Home - New blogpost not available, so not yet linked
-- Learn - I kind of disagree about adding a subnav to a page that basically links to links within the same page that only link to other pages (Videos, FAQ). Perhaps we can discuss options?
P4
-- Learn - For StarlingX Videos - I went ahead and linked straight to our YouTube playlist. Let me know what you think.
-- Learn - Echoing above, I think adding new sections that just link off …
=> Multiple updates per 2.0 marketing release Doc

src/pages/blog/starlingx-release-4.md
=> Add StarlingX 4.0 blog

package.json, src/components/Footer.js, src/pages/community/index.md, src/pages/faq/index.md, src/pages/supporters/index.md
=> Change OpenStack Foundation name to Open Infrastructure Foundation

src/pages/blog/starlingx-2020-annual-report.md
=> Fix link to the source code in 2020 annual report blog

src/content/blog-config.json, src/pages/blog/index.js
This patch adds a link to the new description in the StarlingX
docs about how to contribute a new blog post to the website.
=> Add link to blog contribution guidelines

src/pages/author/sabeel-ansari, src/pages/blog/starlingx-certificate-lcm.md
This patch adds a blog post to describe the new LCM management workflow
in StarlingX 6.0 to automate certificate management.
The blog post will be ublished after the 6.0 release comes out in
January, 2022.
=> Add blog post for Cert Management LCM

src/pages/index.md
This patch adds a pointer to the new low-latency demo video
that is hosted on Youtube and added to the StarlingX playlist.
=> Add low-latency demo link

src/pages/software/index.md
This patch replaces the embedded video on the software tab
to a newer presentation about the platform.
=> Replace video on SW page to newer one

src/pages/blog/starlingx-release-7.md
The publish date of the 7.0 release overview blog post was incorrect. This patch fixes that.
=> Fix 7.0 blog publish date

src/pages/index.md
This change adds a new button to point directly to the ISO images for StarlingX. The new button is placed alongside the existing ones under the mission statement.
=> Adding new button to the homepage

src/pages/blog/starlingx-vptg-march-2023-recap.md
This patch adds the first blog post to recap the PTG sessions that the community held at the event in March.
=> Add blog post about the recent PTG sessions

src/pages/blog/starlingx-vptg-march-2023-recap.md
This patch fixes the headers in the recently added PTG summary blog post.
=> Fix formatting of PTG blog post

src/pages/blog/starlingx-vptg-march-2023-recap-part-2.md
This commit adds the second article to cover the updates and highlights of the community's discussions at the recent PTG sessions.
=> Add PTG summary blog post, part 2

package.json, yarn.lock
Update `gatsby-remark-google-analytics-track-links` to include this fix https://github.com/jamessimone/gatsby-remark-google-analytics-track-links/commit/d6a27187f9dd389fdaa8a2ac1dcd1398e71c4536 that was causing errors on this deploy  #263
ref: https://tipit.avaza.com/project/view/188886#!tab=task-pane&task=3537116
Signed-off-by: Tomás Castillo <tcastilloboireau@gmail.com>
=> Update remark ga track links version

src/pages/blog/starlingx-vptg-april-2024-recap.md
This patch adds the first article in a 2-post series to summarize the highlights of the community's sessions at the recent vPTG in April, 2024.
=> Add vPTG blog post

src/pages/blog/starlingx-vptg-april-2024-recap-2.md
This patch adds the second article in a 2-post series to summarize the highlights of the community's sessions at the recent vPTG in April, 2024.
=> Add part 2 of vPTG summary article

src/pages/blog/starlingx-apparmor.md
This patch fixes camel casing and a typo in the title of the AppArmor blog post that was published in May, 2024..
=> Fix typo in blog title

src/pages/author/andre-zelak.md, src/pages/blog/starlingx-ptp-redundant-ptp-timing-clock-sources.md
Adds markdown files for the blog post and author information.
=> Add blog post for StarlingX PTP redundant timing clock sources

src/pages/blog/starlingx-vptg-october-2024-recap.md
This patch adds a blog post that summarizes the discussions from the recent StarlingX PTG session in October, 2024.
=> Add PTG overview blog post

src/content/footer-nav.json
This patch adds a link to the vulnerability reporting process in the footer of the website, to make it easier for people to discover.
=> Update the website footer
