StarlingXWeb/starlingx-website

- site/learn/index.md
> fix a little typo in website text

- site/blog/starlingx-meetup-january-2019.md
The blog is a summary about the Contirbutor Meetup held in
Chandler Arizona two weeks ago. It contains pointers to the discussed
items and further StarlingX resources.
> Adding new blog entry to StarlingX blog

- site/faq/index.md
Closes-Bug: #1808434
Signed-off-by: Scott Rifenbark <srifenbark@gmail.com>
> index.md: Corrected several typos in the FAQ.

- site/blog/starlingx-meetup-september-2019.md
> Cros linking related blog posts

- site/blog/starlingx-shanghai-recap.md
Adding a new blog post about the recent Shanghai Summit activities
around StarlingX.
> Blog post to recap the Shanghai Summit and PTG

- site/blog/starlingx-cengn-collaboration.md
Adding a blog post to highlight how CENGN is participating in the StarlingX community.
> CENGN collab blog post

- site/learn/index.md
> Updating the overview slide deck on web

- site/learn/index.md
> Generalize the file name of the overview slide deck

- site/.vuepress/components/HomeAnnouncement.vue
- site/index.md
> Fixing 3.0 release refernces on the front page

- site/blog/starlingx-meetup-february-2020.md
> Add blog post about recent StarlingX Contributor Meetup

- src/pages/faq/index.md
> Fix the broken link for the slide templates

- src/pages/index.md
The release should be out this week or early next, merge this after the blog post in https://github.com/StarlingXWeb/starlingx-website/pull/89 is merged.
> Update web to refer to the new 4.0 release

- src/pages/blog/starlingx-ptp-part-1.md
> Add blog post about PTP part 1

- src/pages/blog/starlingx-open-infra-summit-2020.md
> Adding blog post about Open Infra Summit schedule

- src/pages/blog/starlingx-2020-annual-report.md
> Add 2020 Annual Report blog post

- gatsby-browser.js
- gatsby-ssr.js
- src/components/SEO.js
- src/content/site-metadata.json
- src/pages/blog/index.js
- src/templates/community-page.js
- src/templates/faq-page.js
- src/templates/index-page.js
- src/templates/learn-page.js
- src/templates/software-page.js
- src/templates/supporters-page.js
Signed-off-by: Tomás Castillo <tcastilloboireau@gmail.com>
> Fix twitter cards and OG tags

- gatsby-config.js
- src/components/Subscribe.js
- src/style/modules/_search.scss
* Replaces the form with a button that opens a popup to sign up to news, so the user isn't redirected and stays on the page.
Signed-off-by: Tomás Castillo <tcastilloboireau@gmail.com>
> change subscription form for link button

- src/pages/blog/starlingx-release-5.md
> Adding 5.0 release blog post

- src/pages/blog/starlingx-release-5.md
> Fixing timestamp on the StarlingX 5.0 blog post

- src/pages/index.md
> Update reference to 5.0 on the front page

- src/pages/blog/starlingx-ptp-part-1.md
> Link to PTP Part 2 from the Part 1 blog post

- src/pages/blog/starlingx-vptg-october-2021-recap.md
This patch adds a blog post that summarizes the StarlingX
discussions at the recent PTG event.
> Adding summary of the recet vPTG to the blog

- src/pages/blog/starlingx-user-survey-2021.md
> Image placement fix

- src/pages/blog/starlingx-user-survey-2021.md
> Author update

- src/pages/blog/starlingx-2021-annual-report.md
> Adding the 2021 annual report to the blog

- src/pages/blog/starlingx-release-6.md
> Add 6.0 Release overview blog post

- src/pages/index.md
- src/pages/learn/index.md
> Updating video content

- src/pages/software/index.md
> Updating the video link on the Software tab

- src/pages/learn/index.md
- src/pages/software/index.md
> Fix video starting times

- src/pages/learn/index.md
- src/pages/software/index.md
> Fix broken links

- src/pages/index.md
This patch adds the pointer to the latest demo video to
display on the main page.
> Add demo video

- src/pages/blog/starlingx-debian-technology-preview-in-release-7.md
r7 Debian tech preview blog entry available for review.
> Add StarlingX Debian tech preview blog article

- src/templates/index-page.js
This patch updates the link to the new StarlingX user survey that replaces the current one.
> Update the user survey link

- src/pages/blog/starlingx-vptg-october-2022-recap.md
> Add blog post to cover the Fall OpenInfra PTG

- src/pages/index.md
This patch addes the new mission statement to the front page of the website.
> Updating the project's mission statement

- src/pages/blog/starlingx-vptg-october-2023-recap.md
This patch adds a blog post that covers the highlights of the StarlingX community's vPTG sessions.
> Add recap of October, 2023 vPTG Starlingx sessions

- src/pages/author/luis-huapaya.md
- src/pages/blog/starlingx-securing-secrets.md
This patch adds a new blog post authored by Luis Huapaya.
> Adding new blog post about security and secrets

- src/pages/blog/starlingx-deploying-your-app-2.md
This patch fixes the timestamp formatting on the blog.
> Update timestamp starlingx-deploying-your-app-2.md

- src/pages/blog/starlingx-deploying-your-app-2.md
Reverts StarlingXWeb/starlingx-website#256
> Revert "Update timestamp starlingx-deploying-your-app-2.md"

- src/pages/blog/starlingx-enabling-the-intelligent-edge.md
This patch switches the day and month in the timestamp to have it show up on the Blog webpage correctly.
> Update timestamp starlingx-enabling-the-intelligent-edge.md

- src/pages/blog/starlingx-release-9.md
- src/pages/index.md
This patch updates the website with references to the new, 9.0 release of Starlingx. It also adds a blog post that describes the new features and enhancements in the plaform.
> Release announcement blog post and updates

- src/pages/blog/starlingx-certificate-lcm.md
- src/pages/blog/starlingx-debian-technology-preview-in-release-7.md
- src/pages/blog/starlingx-enabling-the-intelligent-edge.md
- src/pages/blog/starlingx-oran-o2-application.md
- src/pages/blog/starlingx-release-3.md
- src/pages/blog/starlingx-release-4.md
- src/pages/blog/starlingx-release-5.md
- src/pages/blog/starlingx-release-6.md
- src/pages/blog/starlingx-release-7.md
- src/pages/blog/starlingx-release-8.md
- src/pages/blog/starlingx-single-core-platform.md
- src/pages/index.md
- src/pages/software/index.md
Reverts StarlingXWeb/starlingx-website#263
> Revert "Updating image mirror links"

- src/pages/blog/starlingx-release-9.md
- src/pages/index.md
Reverts StarlingXWeb/starlingx-website#264
> Revert "Revert "Release announcement blog post and updates""

- src/pages/blog/starlingx-certificate-lcm.md
- src/pages/blog/starlingx-debian-technology-preview-in-release-7.md
- src/pages/blog/starlingx-enabling-the-intelligent-edge.md
- src/pages/blog/starlingx-oran-o2-application.md
- src/pages/blog/starlingx-release-3.md
- src/pages/blog/starlingx-release-4.md
- src/pages/blog/starlingx-release-5.md
- src/pages/blog/starlingx-release-6.md
- src/pages/blog/starlingx-release-7.md
- src/pages/blog/starlingx-release-8.md
- src/pages/blog/starlingx-single-core-platform.md
- src/pages/index.md
- src/pages/software/index.md
This PR includes the changes from #263 that were previously failing on preview deploy
ref: https://tipit.avaza.com/project/view#!tab=task-pane&task=3537116
Signed-off-by: Tomás Castillo <tcastilloboireau@gmail.com>
> Updating image mirror links

- src/pages/blog/starlingx-deploying-your-app-3.md
This blog pull request pushes the final blog post from the Encora StarlingX Team, in which we highlight the knowledge we have gained when deploying our own applications into StarlingX. This part, specifically, highlights installing STX applications with the StarlingX Application Manager.
> Final part of deploying-your-stx-app post series

- src/content/footer-nav.json
- src/pages/messaging-guide/index.md
- src/pages/supporters/index.md
- src/style/modules/_article.scss
- src/templates/messaging-guide-page.js
- src/templates/supporters-page.js
This patch adds a new tab that contains documentation that gives guidelines on how to talk about and advertize the project in social media and other forums.
> New Messaging Guide page

- src/pages/faq/index.md
This patch updates outdated information on the FAQ page of the StarlingX website.
> Update FAQ page

- src/content/top-bar.json
- src/pages/blog/starlingx-release-10.md
- src/pages/index.md
This patch adds a new blog post that contains the announcement and hoghlights of the new 10.0 release of the StarlingX platform.
> Add Release 10.0 blog post

- src/content/top-bar.json
This patch updates the website banner to highlight the price increase for the OpenInfra Summit Europe event.
> Update website banner
